name: text_to_spech
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0-323.2.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.8
  hexcolor: ^3.0.1
  freezed_annotation: ^2.4.4
  freezed: ^2.5.7
  get_it: ^8.0.0
  voice_message_package: ^2.2.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.2
  flutter_localization: ^0.2.2
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  dio: ^5.7.0
  retrofit: ^4.4.1
  retrofit_generator: ^9.1.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.12
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  audioplayers: ^6.1.0
  flutter_screenutil: ^5.9.3
  intl: ^0.19.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/icon/
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-SemiBold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
flutter_intl:
  enabled: true
